---
# .github/release-drafter.yml
# See: https://github.com/release-drafter/release-drafter
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  ## ✨ What's New
  $CHANGES

categories:
  - title: "🚀 Features"
    labels: ["feature", "enhancement"]
  - title: "🐛 Bug Fixes"
    labels: ["fix", "bug"]
  - title: "🧰 Maintenance"
    labels: ["chore", "docs", "ci", "build", "refactor"]
  - title: "🏎️ Performance"
    label: "performance"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
version-resolver:
  major:
    labels: ["breaking"]
  minor:
    labels: ["feature"]
  patch:
    labels: ["fix", "bug", "chore", "docs", "ci", "refactor", "performance"]
  default: patch

autolabeler:
  - label: "feature"
    title: ["/^(feat|feature)/i"]
  - label: "fix"
    title: ["/^(fix|bugfix)/i"]
  - label: "docs"
    title: ["/^(docs)/i"]
  - label: "chore"
    title: ["/^(chore)/i"]
  - label: "ci"
    title: ["/^(ci|build)/i"]
  - label: "refactor"
    title: ["/^(refactor|style)/i"]
  - label: "performance"
    title: ["/^(perf)/i"]
