---
# .github/ISSUE_TEMPLATE/bug_report.yml
name: "🐛 Bug Report"
description: "Create a report to help us improve the Market Beacon bot."
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "When I run the bot with the --symbol XYZ, it crashes with a 'KeyError'."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "To Reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Run the command `make run args="--symbol XYZ"`
        2. See error in the console output...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "I expected the bot to fetch trade data for XYZ and print the statistics."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Relevant log output"
      description: "If applicable, copy and paste any relevant log output. Please use code blocks for readability."
      placeholder: |
        ```
        <--- Paste your logs here --->
        ```
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      description: "What operating system are you running the bot on?"
      options:
        - "Linux"
        - "macOS"
        - "Windows"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Market Beacon Version"
      description: "What version of the application are you running? (e.g., from `pyproject.toml`)"
      placeholder: "e.g., v0.1.0"
    validations:
      required: false
