---
# .github/ISSUE_TEMPLATE/feature_request.yml
name: "✨ Feature Request"
description: "Suggest an idea or enhancement for the Market Beacon bot."
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea! Please describe your feature request in detail.

  - type: textarea
    id: related-problem
    attributes:
      label: "Is your feature request related to a problem?"
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
      placeholder: "It's difficult to see the trade volume over the last hour, I have to calculate it manually."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
      placeholder: "Add a new metric to the output called 'Hourly Trade Volume' that shows the total volume of trades
      in the last 60 minutes."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "I considered adding a separate script, but integrating it directly into the main output would
      be more convenient."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
