---
name: CI Pipeline

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      statuses: write
    steps:
      - name: Validate PR Title (Conventional Commits)
        uses: amannn/action-semantic-pull-request@v5.5.3
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  quality-and-test:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install TA-Lib C-library locally
        run: |
          DEPS_DIR=${{ github.workspace }}/ta-lib-build
          mkdir -p $DEPS_DIR
          wget https://github.com/ta-lib/ta-lib/releases/download/v0.6.4/ta-lib-0.6.4-src.tar.gz -O ta-lib.tar.gz
          tar -xzf ta-lib.tar.gz
          cd ta-lib-0.6.4
          ./configure --prefix=$DEPS_DIR
          make
          make install

      - name: Install Python dependencies
        run: uv sync --all-extras --dev
        env:
          DEPS_DIR: ${{ github.workspace }}/ta-lib-build
          CFLAGS: -I${{ github.workspace }}/ta-lib-build/include
          LDFLAGS: -L${{ github.workspace }}/ta-lib-build/lib

      - name: Run Quality and Security Checks
        run: uv run pre-commit run --all-files --show-diff-on-failure

      - name: Run Tests
        run: uv run pytest tests/
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/ta-lib-build/lib

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image for validation
        run: make docker-build
