name: CI

on:
  push:
    branches-ignore:
      - main
      - dev
  pull_request:
    branches-ignore:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          make venv
          make install-dev

      - name: Run tests
        run: make tests
