---
name: Labeler

on:
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  label:
    name: Auto-label PRs
    runs-on: ubuntu-latest
    steps:
      - name: Label PR based on title
        uses: release-drafter/release-drafter@v6.1.0
        with:
          disable-releaser: true
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
